# Generated by Django 4.1.1 on 2023-03-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('name', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=200)),
                ('operating_system', models.CharField(max_length=200)),
                ('processor', models.CharField(max_length=200)),
                ('connectivity', models.CharField(max_length=200)),
                ('rear_camera', models.CharField(max_length=200)),
                ('front_camera', models.CharField(max_length=200)),
                ('battery_charging', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
